repository_type: pipeline

nf_core_version: 3.4.1

lint: {}

template:
  org: nf-core
  name: pira
  description: Short description for pira
  author: Andre Perez
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - gpu
  is_nfcore: true
