# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "GENOME_BED"
description: Convert a reference GTF annotation to BED format
keywords:
  - annotation
  - BED
  - GTF
components:
  - bed
input:
  - ch_gtf:
      type: file
      description: Reference genome GTF annotation to convert to BED format
output:
  - data:
      type: file
      description: Generated BED annotation file
  - versions:
      type: file
      description: Versions of the BED conversion tool
authors:
  - "@andre-marcos-perez"
maintainers:
  - "@andre-marcos-perez"
