# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "GENOME_INDEX"
description: Generate a STAR genome index from reference FASTA and GTF files
keywords:
  - genome
  - index
  - FASTA
  - GTF
  - STAR
components:
  - star/genomegenerate
input:
  - ch_fasta:
      type: file
      description: Reference genome FASTA file
  - ch_gtf:
      type: file
      description: Reference genome GTF annotation
output:
  - data:
      type: directory
      description: Generated STAR genome index directory
  - versions:
      type: file
      description: Versions of STAR used by the subworkflow
authors:
  - "@andre-marcos-perez"
maintainers:
  - "@andre-marcos-perez"
