name: cd
on:
  workflow_call:
    inputs:
      env:
        type: string
        description: |
          Environment which you would like to deploy to (e.g. dev, stage, live).
        required: true
jobs:
  image:
   runs-on: ubuntu-latest
   permissions:
     id-token: write
     contents: read
   steps:
     - name: Checkout repository
       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
       with:
         ref: ${{ github.event.pull_request.head.sha || github.sha }}
